image:
  file: .gitpod.dockerfile

tasks:
  - name: client
    command: |
      cd client
      npm install

  - name: api
    command: |
      cd api
      npm install

  # - name: mongodb
  #   command: |
  #     mkdir -p /workspace/data && mongod --dbpath /workspace/data

ports:
  - name: frontend
    port: 5173
    onOpen: open-browser
    visibility: public
  - name: backend
    port: 4000
    visibility: public
