image:
  file: .gitpod.dockerfile

# tasks:
#   - name: frontend
#     command: |
#       cd frontend
#       npm install

  # - name: backend
  #   command: |
  #     cd backend
  #     npm install

  # - name: mongodb
  #   command: |
  #     mkdir -p /workspace/data && mongod --dbpath /workspace/data

ports:
  - name: frontend
    port: 5173
    onOpen: open-browser
    visibility: public
  - name: backend
    port: 4000
    visibility: public
